version: "3"
services:
  app:
    container_name: trunk-api-node
    restart: always
    build: .
    ports:
      - "80:3000"
    links:
      - db
  db:
    container_name: trunk-api-mongo
    image: mongo
    ports:
      - "27017:27017"
